### ISSUE TITLE
TypeError and server stopped after update @adonisjs/core

### ISSUE THREAD

**Issue by thejullius** [Rocketseat/adonis-bull#79]
**Description of bug**

i am getting an error and the server is stopping after update @adonisjs/core from `5.0.4-preview-rc` to `5.1.5`

**To Reproduce**

Just update @adonisjs/core to 5.1.5

**Exception or Error**
<pre><code>
TypeError: this.container.bind is not a function

1 BullProvider.register
  /home/workspace/node_modules/@rocketseat/adonis-bull/build/providers/BullProvider.js:11

2 anonymous
  /home/workspace/node_modules/@adonisjs/fold/build/src/Registrar/index.js:103

3 Registrar.register
  /home/workspace/node_modules/@adonisjs/fold/build/src/Registrar/index.js:101

4 anonymous
  /home/workspace/node_modules/@adonisjs/application/build/src/Application.js:530

5 Application.registerProviders
  /home/workspace/node_modules/@adonisjs/application/build/src/Application.js:524

6 HttpServer.wire
  /home/workspace/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:52

7 HttpServer.start
  /home/workspace/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:146

</code></pre>

**Environment:**

Ubuntu 20.04.2 LTS
Node v14.5.0

<pre><code>
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "node ace build --production",
    "start": "node server.js",
    "dev": "node ace serve --watch"
  },
  "devDependencies": {
    "@adonisjs/assembler": "^3.0.0",
    "adonis-preset-ts": "^2.1.0",
    "pino-pretty": "^4.7.1",
    "typescript": "~4.1",
    "youch": "^2.2.1",
    "youch-terminal": "^1.1.0"
  },
  "dependencies": {
    "@adonisjs/core": "~5.1.5",
    "@adonisjs/repl": "^1.0.0",
    "@rocketseat/adonis-bull": "^1.0.0-2",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
}

</code></pre>

 **Additional context**
Works fine with `"@adonisjs/core": "^5.0.4-preview-rc"`

**Comment by thejullius** [comment]
While I investigated the adonis discussions, the creators do not recommend updating anything that starts with @adonisjs until the release comes out.

https://github.com/adonisjs/core/issues/2445#issuecomment-816606933
https://github.com/adonisjs/core/discussions/2424#discussioncomment-532946

So it is recommended to keep the versions of @adonisjs in the latest release.
<pre><code>
    "@adonisjs/ace": "^6.0.0",
    "@adonisjs/assembler": "^3.0.6",
    "@adonisjs/core": "^5.0.4-preview-rc",
    "@adonisjs/lucid": "^10.0.0",
    "@adonisjs/repl": "^1.0.0"
    "@adonis/ANY DEPENDENCY":"LAST RELEASE VERSION"
</pre></code>
@Rocketseat Feel free to close this issue or leave open for reference

**Comment by mxthevs** [comment]
["Out of preview"](https://docs.adonisjs.com/releases/out-of-preview) got released today, and this error will be affecting everyone who decide to update

**Comment by anthrogan** [comment]
Likely caused by the below breaking change
![image](https://user-images.githubusercontent.com/30973884/117489726-ded52380-af65-11eb-826e-0e2f76b2b15a.png)

**Comment by HigoRibeiro** [comment]
Hi @thejullius, this was fixed into PR #81.

I'll apreciate if you can test the new alpha release v1.0.4.
